#!/bin/bash

CRIME_TYPE_ID=$1
CRIME_ID=$2

curl -s "https://www.torn.com/page.php?sid=crimesData&step=attempt&typeID=$CRIME_ID&crimeID=$CRIME_TYPE_ID&value1=$VALUE1" \
  -H "Cookie: PHPSESSID=$PHPSESSID" \
  -H "Cookie: cf_clearance=$CF_CLEARANCE" \
  -H "User-agent: $USER_AGENT"
