#!/bin/bash

curl -s "https://www.torn.com/page.php?sid=crimesData&step=hub" \
  -H "Cookie: PHPSESSID=$PHPSESSID" \
  -H "Cookie: cf_clearance=$CF_CLEARANCE" \
  -H "User-agent: $USER_AGENT" \
  | jq .DB.user
