#!/bin/bash

CRIME_TYPE_ID=$1

curl -s "https://www.torn.com/page.php?sid=crimesData&step=crimesList&typeID=$CRIME_TYPE_ID" \
  -H "Cookie: PHPSESSID=$PHPSESSID" \
  -H "Cookie: cf_clearance=$CF_CLEARANCE" \
  -H "User-agent: $USER_AGENT"
