#!/bin/bash

FILE_NAME=$(openssl rand -hex 16)
CRIME_ID="$(src/features/crime/actions/get_search_for_cash_target_id)"

src/features/crime/actions/attempt 1 "$CRIME_ID" >>"$TORN_HOME/logs/$FILE_NAME"
src/features/crime/actions/report "$TORN_HOME/logs/$FILE_NAME" 1 "$CRIME_ID"
