#!/bin/bash

curl -s 'https://www.torn.com/gym.php?step=getInitialGymInfo' \
  -H "Cookie: PHPSESSID=$PHPSESSID" \
  -H "Cookie: cf_clearance=$CF_CLEARANCE" \
  -H "User-agent: $USER_AGENT" \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw '{"step":"getInitialGymInfo"}'
