#!/bin/bash

STAT=$1
curl -s 'https://www.torn.com/gym.php?step=train' \
  -H "Cookie: PHPSESSID=$PHPSESSID" \
  -H "Cookie: cf_clearance=$CF_CLEARANCE" \
  -H "User-agent: $USER_AGENT" \
  -H 'x-requested-with: XMLHttpRequest' \
  --data-raw '{"step":"train","stat":"'"$STAT"'","repeats":1}'
