#!/bin/bash

ITEM_ID=$1
AMOUNT=$2
DESCRIPTION=$3

FILE_NAME=$(openssl rand -hex 16)
src/features/common/actions/get_info/item "$ITEM_ID" >>"$TORN_HOME/logs/$FILE_NAME"

NAME="$(jq -r .name "$TORN_HOME/logs/$FILE_NAME")"
TYPE="$(jq -r .type "$TORN_HOME/logs/$FILE_NAME")"
ID="$(jq .id "$TORN_HOME/logs/$FILE_NAME")"

RESET="\033[0m"
BOLD="\033[1m"
DIM="\033[2m"
CYAN="\033[36m"

TIMESTAMP=$(date +"%H:%M:%S")

printf "%b[%s]%b %b%s%b %b#%s%b %b%s%b %bx%s%b %b- %s%b\n" \
  "$DIM" "$TIMESTAMP" "$RESET" \
  "$DIM" "$TYPE" "$RESET" \
  "$BOLD" "$ID" "$RESET" \
  "$CYAN$BOLD" "$NAME" "$RESET" \
  "$DIM" "$AMOUNT" "$RESET" \
  "$DIM" "$DESCRIPTION" "$RESET"
