#!/bin/bash

ALL_TYPES=('defense' 'speed' 'dexterity' 'strength')

for TYPE in "${ALL_TYPES[@]}"; do
  VAR_NAME=$(printf 'GYM_%s' "$TYPE" | tr '[:lower:]' '[:upper:]')
  VALUE="${!VAR_NAME}"

  if [ "$VALUE" = "true" ]; then
    FILE_NAME=$(openssl rand -hex 16)
    src/features/gym/actions/step "$TYPE" >> "$TORN_HOME/logs/$FILE_NAME"
    src/features/gym/actions/report "$TORN_HOME/logs/$FILE_NAME" "$TYPE"
  fi
done
