#!/bin/bash

XID=$1

curl -s 'https://www.torn.com/profiles.php?step=getProfileData&XID='"$XID"\
  -H "Cookie: PHPSESSID=$PHPSESSID" \
  -H "Cookie: cf_clearance=$CF_CLEARANCE" \
  -H "User-agent: $USER_AGENT" \
  -H 'x-requested-with: XMLHttpRequest' |
  jq .
